name: Update version on Release Branch

on:
  push:
    branches:
      - release/* # Trigger on any push to branches starting with 'release/'

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is needed to push commits
    
    steps:
      # Step 1: Checkout the repository code with the release branch
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need all history for tags
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Step 2: Extract version number from branch name (release/x.x.x -> x.x.x)
      - name: Extract Version
        id: extract_version
        run: |
          BRANCH_NAME="${{ github.ref_name }}" # This gets the branch name that triggered the workflow
          VERSION=${BRANCH_NAME#release/}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION from branch $BRANCH_NAME"
      
      # Step 3: Update version in pubspec.yaml and push to the same branch
      - name: Update Pubspec Version
        run: |
          VERSION=${{ steps.extract_version.outputs.VERSION }}
          BRANCH_NAME="${{ github.ref_name }}"
          
          echo "Updating pubspec.yaml with version: $VERSION"
          # Use sed to replace the version line in pubspec.yaml
          sed -i "s/^version: .*/version: $VERSION/" pubspec.yaml
          
          # Check if there are changes to commit
          if ! git diff --quiet pubspec.yaml; then
            # Commit the change
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add pubspec.yaml
            git commit -m "Bump version to $VERSION"
            
            # Push back to the same release branch
            git push origin HEAD
            echo "Updated pubspec.yaml with version $VERSION and pushed to $BRANCH_NAME"
          else
            echo "pubspec.yaml already has version $VERSION, no changes needed"
          fi
    